name: test-workflows

on:
  push:
    branches: [ "main" ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          conda update -n test-workflows-env -c defaults conda
          conda env update --file devtools/conda-envs/test_env.yaml --name test-workflows-env
          conda activate test-workflows-env

      - name: Test with pytest
        run: |
          which pytest

