name: test-workflows

on:
  push:
    branches: [ "main" ]
    paths:
￼      - 'conda-envs/test_env.yaml'
￼      - '.github/workflows/test.yaml'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          conda update conda
          conda env update -f devtools/conda-envs/test_env.yaml -n base

      - name: Test with pytest
        run: |
          which pytest

