name: test-workflows
on:
  push:
    branches: ["main"]
    paths:
      - 'devtools/conda-envs/test_env.yml'
      - '.github/workflows/test.yaml'
  pull_request:
    branches: ["main"]

jobs:
  test-ubuntu:
    name: test on ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: conda-forge,defaults
          use-only-tar-bz2: true
          auto-activate-base: true
          auto-update-conda: true
          #activate-environment: test_env
          #environment-file: devtools/conda-envs/test_env.yaml

        #run:
        #  conda update conda
        #  conda env update -f devtools/conda-envs/test_env.yaml -n base

      - name: install dependencies
        run: |
          echo "begin: PATH=$PATH;"

          conda env create --name test_env --file devtools/conda-envs/test_env.yml
          conda activate test_env || true
          conda list || true
          echo "after conda activate test_env: PATH=$PATH;"
          which pytest || true
          pytest --version || true


      - name: Test with pytest
        run: |
          which pytest || true
          pytest --version || true

      # bind to tda-qchem-explorations
      - uses: actions/checkout@v2
        with:
          repository: "tda-qchem/tda-qchem-explorations"
          ref: "main"
          path: "tda-qchem-explorations"
        name: Checkout scratch TDA-QCHEM data

    - name: Run Python scripts on tda-qchem-explorations data
      run: |
        cd tda-qchem-explorations
        python3 -u python/run.py






