name: test-workflows

on:
  push:
    branches: [ "main" ]
    paths:
      - 'conda-envs/test_env.yaml'
      - '.github/workflows/test.yaml'
  pull_request:
    branches: [ "main" ]

jobs:

  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
        
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Update conda
        uses: actions/update-conda@v2
        # todo
        ##Downloading the latest Miniconda installer for macOS. Your architecture may vary.
        #curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/miniconda.sh
        ##Downloading the latest Miniconda installer for Linux. Your architecture may vary.
        #wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
        #bash ~/miniconda.sh -b -p $HOME/miniconda
        
      - name: Setup environment
        uses: actions/setup-env@v2
        run: |
          conda-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: test_env
          environment-file: conda-envs/test_env.yaml

    - name: Install dependencies
      run: |
        conda env update --file ${{ environment-file }} --name base

    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest

